palabra = input("Introduce una palabra: ")
num_int = int (input ("Introduce un numero entero: "))
num_float = float (input ("Introduce un numero flotante: "))
num_complex = complex (input ("Introduce un numero complejo: "))
print ("Estos son los valores:")
print ("String: ",palabra)
print ("NumeroEntero: ",num_int)
print ("NumeroFlotante: ",num_float)
print ("Numero Complejo: ",num_complex)

